name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check json files
        run: |
            cd metadata
            for n in *; do printf '%s\n' "$n"; done >> ../json.list
            while read -r i; do
              if jq -e . >/dev/null 2>&1 <<<"$(cat $i)"; then
                echo "Parsed JSON successfully and got something other than false/null"
              else
                echo "Failed to parse JSON $i, or got false/null"
                exit 1
              fi
            done < ../json.list
